version: 2
updates: []

# version: 2
# updates:
#     - package-ecosystem: github-actions
#       directory: "/"
#       schedule:
#           interval: weekly
#       open-pull-requests-limit: 3
#       target-branch: development
#       commit-message:
#           prefix: "[DEPENDABOT]"

#     - package-ecosystem: pip
#       directory: "/.github/workflows"
#       schedule:
#           interval: weekly
#       open-pull-requests-limit: 3
#       target-branch: development
#       commit-message:
#           prefix: "[DEPENDABOT]"

#     - package-ecosystem: pip
#       directory: "/docs"
#       schedule:
#           interval: weekly
#       open-pull-requests-limit: 3
#       target-branch: development
#       commit-message:
#           prefix: "[DEPENDABOT]"

#     - package-ecosystem: pip
#       directory: "/"
#       schedule:
#           interval: weekly
#       open-pull-requests-limit: 3
#       target-branch: development
#       commit-message:
#           prefix: "[DEPENDABOT]"
