comment: false
coverage:
    status:
        project:
            default:
                target: 0%
                # target: auto
                threshold: 100%
                # if_ci_failed: success #success, failure, error, ignore
        patch:
            default:
                target: 0%
                # target: auto
                threshold: 100%
                # if_ci_failed: success #success, failure, error, ignore
