name: Build Documentation

on: [push]

jobs:
    build:
        # Here, 'docs-build' is always run on ubuntu-latest so no problem for apt-get
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Check out source-code repository

            - name: Setup Pandoc
              run: |
                  sudo apt-get install -y pandoc

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9

            - name: Install pip
              run: |
                  python -m pip install --upgrade pip

            - name: Install doc dependencies
              run: |
                  pip install -r docs/requirements.txt

            - name: Build docs
              run: |
                  cd docs
                  make html

            - name: Deploy
              if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}}
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html
